Grails内置支持http://en.wikipedia.org/wiki/Content_negotiation[内容协商]，可以使用HTTP `Accept` 标头、显式格式请求参数或已映射的URI的扩展来进行内容协商。

==== 配置MIME类型

在您开始处理内容协商之前，您需要告诉Grails您希望支持的内容类型。默认情况下，Grails在 `grails-app/conf/application.yml` 中使用 `grails.mime.types` 设置配置了许多不同的内容类型：

[source,yaml]
----
grails:
    mime:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
----

设置也可以在 `grails-app/conf/application.groovy` 中完成，如下所示：

[source,groovy]
----
grails.mime.types = [ // the first one is the default format
    all:           '*/*', // 'all' maps to '*' or the first available format in withFormat
    atom:          'application/atom+xml',
    css:           'text/css',
    csv:           'text/csv',
    form:          'application/x-www-form-urlencoded',
    html:          ['text/html','application/xhtml+xml'],
    js:            'text/javascript',
    json:          ['application/json', 'text/json'],
    multipartForm: 'multipart/form-data',
    rss:           'application/rss+xml',
    text:          'text/plain',
    hal:           ['application/hal+json','application/hal+xml'],
    xml:           ['text/xml', 'application/xml']
]
----

以上配置使Grails能够检测请求的格式，其中包含'text/xml'或'application/xml'媒体类型，简单地选择'xml'。您可以通过向映射中添加新条目来添加自己的类型。第一个是默认格式。

==== 使用格式请求参数进行内容协商

假设控制器操作可以以多种格式返回资源：HTML、XML和JSON。客户端会收到什么格式？客户端控制这一点的最简单、最可靠的方式是通过 `format` URL 参数。

因此，如果您作为浏览器或其他客户端希望获得XML格式的资源，可以使用以下URL：

[source]
----
http://my.domain.org/books.xml
----

注意：请求参数 `format` 也被允许，例如 `http://my.domain.org/books?format=xml` ，但默认的Grails URL映射 `get \"/$controller(.$format)?\"(action:\"index\")` 将用null覆盖 `format` 参数。因此，默认映射应更新为 `get \"/$controller\"(action:\"index\")` 。

服务器端的结果是 `response` 对象上的 `format` 属性值为 `xml` 。

您也可以在链接：theWebLayer.html#urlmappings[URL映射]定义中定义此参数：

[source,groovy]
----
\"/book/list\"(controller:\"book\", action:\"list\") {
    format = \"xml\"
}
----

您可以编写控制器操作以基于此属性返回XML，但也可以使用专门的控制器 `withFormat()` 方法：

注意：此示例需要添加 `org.grails.plugins:grails-plugin-converters` 插件

[source,groovy]
----
import grails.converters.JSON
import grails.converters.XML

class BookController {

    def list() {
        def books = Book.list()

        withFormat {
            html bookList: books
            json { render books as JSON }
            xml { render books as XML }
            '*' { render books as JSON }
        }
    }
}
----

在此示例中，Grails只会执行与请求的内容类型匹配的 `withFormat()` 中的代码块。因此，如果首选格式为 `html` ，则Grails将只执行 `html()` 调用。每个'代码块'可以是用于对应视图的映射模型（如上例中用于 'html' 的部分）或一个闭包。闭包可以包含任何标准行为代码，例如可以返回一个模型或直接呈现内容。

当没有明确匹配的格式时，可以使用 `*` （通配符）代码块来处理所有其他格式。

有一个特殊的格式，"all"，它与明确格式不同。如果指定了 "all"（通常通过Accept标头 - 见下文），那么当没有 `*` （通配符）块可用时，将执行 `withFormat()` 的第一个代码块。

您不应该添加明确的 "all" 块。在此示例中，格式为 "all" 将触发 `html` 处理程序（ `html` 是第一个代码块，且没有 `*` 块）。

[source,groovy]
----
withFormat {
    html bookList: books
    json { render books as JSON }
    xml { render books as XML }
}
----

注意：使用链接:../ref/Controllers/withFormat.html[withFormat] 时，请确保它是控制器操作中的最后一个调用，因为 `withFormat` 方法的返回值被操作用来决定接下来发生什么。

==== 使用Accept标头

每个传入的HTTP请求都有一个特殊的http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html[Accept] 标头，定义了客户端可以"接受"的媒体类型（或MIME类型）。在旧版浏览器中，通常是这样的：

[source]
----
*/*
----

这只是意味着任何内容。但是，更新的浏览器会发送更有趣的值，例如Firefox发送的：

[source]
----
text/xml, application/xml, application/xhtml+xml, text/html;q=0.9, \
    text/plain;q=0.8, image/png, */*;q=0.5
----

此特定的接受标头是没有用的，因为它表明XML是首选的响应格式，而用户实际上希望的是HTML。这就是为什么Grails默认情况下会忽略浏览器的Accept标头。但是，非浏览器客户端通常在需求上更具体，可以发送Accept标头，例如

[source,groovy]
----
application/json
----

如前所述，Grails的默认配置是忽略浏览器的Accept标头。这是通过配置设置 `grails.mime.disable.accept.header.userAgents` 完成的，该设置用于检测主要呈现引擎并忽略其ACCEPT标头。这使Grails的内容协商可以继续为非浏览器客户端工作：

[source,groovy]
----
grails.mime.disable.accept.header.userAgents = ['Gecko', 'WebKit', 'Presto', 'Trident']
----

例如，如果看到上面的接受标头（'application/json'），那么将将 `format` 设为 `json` ，就像您期望的那样。当然，这也适用于 `withFormat()` 方法，方式与设置 `format` URL参数时一样（尽管URL参数优先）。

一个为 '\\*/\\*' 的接受标头将导致 `format` 属性的值为 `all` 。

注意：如果使用 accept 标头，但不包含任何注册的内容类型，Grails会假定是有问题的浏览器在发出请求，并设置HTML格式 - 请注意，这与其他内容协商模式的工作方式不同，因为其他模式会激活 "all" 格式！

==== 请求格式 vs. 响应格式

从Grails 2.0开始，有一个单独的请求格式和响应格式的概念。请求格式由 `CONTENT_TYPE` 标头确定，并通常用于检测传入请求是否可以解析为XML或JSON，而响应格式使用文件扩展名、格式参数或ACCEPT标头来尝试向客户端提供适当的响应。

链接：../ref/Controllers/withFormat.html[withFormat] 可用于控制器中处理响应格式的相关内容。如果要添加处理请求格式的逻辑，可以使用请求上可用的单独 `withFormat` 方法来完成：

[source,groovy]
----
request.withFormat {
    xml {
        // 读取XML
    }
    json {
        // 读取JSON
    }
}
----

==== 使用URI扩展进行内容协商

Grails还支持使用URI扩展进行内容协商。例如，给定以下URI：

[source]
----
/book/list.xml
----

这是因为默认URL映射定义如下：

[source,groovy]
----
\"/$controller/$action?/$id?(.$format)?\"{
----

注意路径中包含 `format` 变量。如果不希望使用文件扩展名进行内容协商，则可以简单地删除URL映射的此部分：

[source,groovy]
----
\"/$controller/$action?/$id?\"{
----


==== 测试内容协商

要测试单元测试或集成测试中的内容协商（请参阅链接：testing.html[测试]一节），可以操纵传入请求标头：

[source,groovy]
----
void testJavascriptOutput() {
    def controller = new TestController()
    controller.request.addHeader \"Accept\",
              \"text/javascript, text/html, application/xml, text/xml, */*\"

    controller.testAction()
    assertEquals \"alert('hello')\", controller.response.contentAsString
}
----

或者可以设置格式参数以实现类似效果：

[source,groovy]
----
void testJavascriptOutput() {
    def controller = new TestController()
    controller.params.format = 'js'

    controller.testAction()
    assertEquals \"alert('hello')\", controller.response.contentAsString
}
----