如果您有兴趣为grails的任何部分贡献修复和功能，您将需要学习如何获取项目的源代码，构建项目并使用您自己的应用程序进行测试。在开始之前，请确保您具有以下内容：

* JDK（11或以上）
* git客户端

一旦您安装了所有先决条件包，下一步是下载Grails源代码，该源代码托管在http://github.com[GitHub]中，由http://github.com/grails[\"grails\" GitHub用户]拥有多个存储库。这只是克隆您感兴趣的存储库的一个简单例子。例如，要获取核心框架，请运行：

[source,groovy]
----
git clone http://github.com/grails/grails-core.git
----

这将在您当前工作目录中创建一个“grails-core”目录，其中包含所有项目源文件。下一步是从源中获取Grails安装。

=== 创建Grails安装

如果您查看项目结构，您会发现它看起来并不像一个标准的`GRAILS_HOME`安装。但是，简单将其变为一个标准。只需从项目的根目录运行以下命令：

[source,groovy]
----
./gradlew install
----

这将获取Grails所需的所有标准依赖项，然后构建一个`GRAILS_HOME`安装。请注意，该目标跳过了大量的Grails测试类集合，这可能需要一些时间完成。

完成以上命令后，只需将`GRAILS_HOME`环境变量设置为检出目录，并将“bin”目录添加到您的路径中。当您下次键入`grails`命令运行时，您将使用您刚刚构建的版本。

如果您使用http://sdkman.io[SDKMAN]，则还可以通过以下方式使用本地安装：

[source,groovy]
----
sdk install grails dev /path/to/grails-core
----

您还需要将本地安装发布到本地maven。
----
./gradlew pTML
----

现在，您将在本地拥有一个dev版本，可以用来测试您的功能。

=== 运行测试套件

要运行完整的测试套件，您只需执行以下操作：

[source,groovy]
----
./gradlew test
----

这将需要一些时间（15-30分钟），因此考虑使用命令行运行单个测试。例如，要运行测试规范`BinaryPluginSpec`，只需执行以下命令：

[source,groovy]
----
./gradlew :grails-core:test --tests *.BinaryPluginSpec
----

请注意，您需要指定测试用例所在的子项目，因为顶级“test”目标将无法正常工作。...

=== 在IntelliJ IDEA中开发

您需要运行以下gradle任务：

[source,groovy]
----
./gradlew idea
----

然后在生成的IDEA中打开项目文件。简单！

=== 在STS / Eclipse中开发

您需要运行以下gradle任务：

[source,groovy]
----
./gradlew cleanEclipse eclipse
----

在将项目导入STS之前，执行以下操作：

* 编辑grails-scripts/.classpath并删除“<classpathentry kind=\"src\" path=\"../scripts\"/>”这一行。

使用“Import->General->Existing Projects into Workspace”将所有项目导入STS。可能会出现一些构建错误。要修复这些错误，请执行以下操作：

* 将springloaded-core JAR文件添加到$GRAILS_HOME/lib/org.springsource.springloaded/springloaded-core/jars到grails-core的classpath。
* 从grails-plugin-testing的源路径GRECLIPSE-1067中删除“src/test/groovy”。
* 将jsp-api JAR文件添加到$GRAILS_HOME/lib/javax.servlet.jsp/jsp-api/jars到grails-web的classpath。
* 修复grails-scripts的源路径。添加链接的源文件夹链接到“../scripts”。
* 执行整个工作区的清除构建。
* 使用Eclipse GIT scm团队提供程序：选择导航中的所有项目（除了\"Servers\"）右键单击-> Team -> Share project（而不是\"Share projects\"）。选择“Git”。然后选中“在项目的父文件夹中使用或创建存储库”并点击“完成”。
* 从邮件列表线程http://grails.1312388.n4.nabble.com/Grails-development-code-style-IDE-formatting-settings-tp3854216p3854216.html[获得推荐的代码样式设置]（最终样式尚未确定，当前为http://grails.1312388.n4.nabble.com/attachment/3854262/0/profile.xml[profile.xml]）。在STS中导入代码样式xml文件Window->Preferences->Java->Code Style->Formatter->Import。Grails代码使用空格而不是制表符进行缩进。

=== 调试Grails或Grails应用程序

要开启调试，请运行：

[source,groovy]
----
./gradlew bootRun --debug-jvm
----

默认情况下，Grails会fork一个JVM来运行应用程序。`-debug-jvm`参数将使调试器与forked JVM相关联。