如果您想向该项目提交补丁，您只需要在GitHub上fork存储库，而不是直接克隆它。然后，您将提交更改到您的fork，并发送拉取请求以供核心团队成员审查。

=== Forking和Pull请求

http://github.com[GitHub]的一个好处是您可以通过https://help.github.com/articles/fork-a-repo/ [fork存储库] 和https://help.github.com/articles/creating-a-pull-request/ [发送拉取请求] 与您的更改轻松地为项目做出贡献。

接下来是一些指导方针，帮助确保您的拉取请求得以迅速处理并提供我们需要的信息。 这也会让您的生活更轻松！

==== 确保您的fork是最新的

对过时的源代码进行更改并不明智。 可能有其他人已经做出了更改。
[source, groovy]
----
git pull upstream master
----

==== 为您的更改创建本地分支

如果您为更改创建本地分支，您的生活将变得更简单。 例如，一旦您fork一个存储库并将fork克隆到本地，立即执行
[source, groovy]
----
git checkout -b issue_123
----

这将基于“master”分支创建一个名为“issue_123”的新本地分支。 当然，您可以按照自己的喜好命名分支，但一个好主意是参考与更改相关的GitHub问题号。 每个拉取请求应该有自己的分支。

==== 为非常规更改创建Github问题

对于任何非常规更改，请在github上提出问题（如果尚不存在）。 这有助于我们跟踪每个新版本中引入的更改。

==== 在提交消息中包含github问题ID

这可能看起来并不特别重要，但在提交消息中包含github问题ID意味着我们可以在以后找出更改的原因。 在与该问题相关的所有提交中都包含ID。 如果提交与问题无关，则无需包含问题ID。

==== 确保您的fork再次更新并rebase

由于核心开发人员必须将您的提交合并到主存储库中，因此在发送拉取请求之前，确保GitHub上的fork是最新的会使生活变得轻松。
 
假设您已将主存储库设置为称为“upstream”的远程存储库，并且要提交拉取请求。 此外，您所有的更改目前都在本地“issue_123”分支上，而不在“master”上。 第一步涉及从自上次获取和合并以来添加的任何更改中提取任何更改：
[source, groovy]
----
git checkout master
git pull upstream master
----

这应该可以在没有任何问题或冲突的情况下完成。 接下来，根据现在最新的主支重新对您的本地分支进行rebase：
[source, groovy]
----
git checkout issue_123
git rebase master
----

这样做会重排提交，使得所有更改都在最近的主分支更改之后。 考虑将一些卡片添加到卡组的顶部，而不是将它们混合到卡组中。

==== 将您的分支推送到GitHub并发送拉取请求

最后，您必须将更改推送到GitHub上的fork，否则核心开发人员将无法获取它们：
 
[source, groovy]
----
git push origin issue_123
----

注意：您不应合并分支到您的fork的主分支。 如果拉取请求未被接受，则您的主分支将永远与上游不同步。
现在您准备从GitHub用户界面发送拉取请求。

==== 告诉您的拉取请求是为什么的

拉取请求可以包含任意数量的提交，并且可能与任意数量的问题相关联。 在拉取请求消息中，请指定与请求相关的所有问题的ID。 同样，简要描述您所做的工作，例如：“我重构了数据绑定器并添加了对自定义数字编辑器的支持。 修复#xxxx”。