Grails新的命令行界面（CLI）与以前的版本相比已经发生了重大变化，主要集中在代码生成方面。一个值得注意的改变是去除了用于调用Gradle进行构建相关任务的API。这种责任转移与框架的演进以及其与Gradle构建系统的集成一致。

=== 访问Grails CLI

Grails CLI（命令行界面）可以通过在终端或命令提示符中简单地键入以下命令来快速轻松地访问：

[source,shell]
----
grails
----

这个命令允许开发人员快速启动Grails CLI并开始使用该框架进行工作，为那些想要启动Grails项目的人提供了一个简单的入口点。

新的Grails CLI！是启动新Grails项目的首选方法。这个命令行界面提供了各种选项来创建项目，让您选择首选的构建工具、测试框架、GORM实现等。此外，CLI还提供了为生成控制器和领域类等必要组件的命令。

=== Grails Forge网站

您还可以通过访问https://start.grails.org/ [Grails Forge网站]来开始您的Grails应用程序，无需安装Grails CLI。这个基于web的平台让您方便地启动Grails项目，无需安装CLI。

=== 理解新的Grails命令行界面（CLI）

一旦成功安装了Grails CLI，您可以使用"grails"命令来激活它。例如：

[source,shell]
----
grails create-app myapp
----

一个Grails框架CLI项目可以通过"grails-cli.yml"文件来识别，如果使用CLI创建，则此文件会自动生成在项目的根目录。此文件包含有关项目配置文件、默认包和其他变量的信息。

这里是一个针对默认Grails web应用程序的"grails-cli.yml"配置示例：

[source,yaml]
----
applicationType: web
defaultPackage: com.example
testFramework: spock
sourceLanguage: groovy
buildTool: gradle
gormImpl: gorm-hibernate5
servletImpl: spring-boot-starter-tomcat
features:
  - app-name
  - asset-pipeline-grails
  - base
  - geb
  - gorm-hibernate5
  - gradle
  - grails-application
  - grails-console
  - grails-dependencies
  - grails-gorm-testing-support
  - grails-gradle-plugin
  - grails-gsp
  - grails-url-mappings
  - grails-web
  - grails-web-testing-support
  - h2
  - logback
  - micronaut-inject-groovy
  - readme
  - scaffolding
  - spock
  - spring-boot-autoconfigure
  - spring-boot-starter
  - spring-boot-starter-tomcat
  - yaml
----

这个"grails-cli.yml"配置设置了Grails web应用程序的各个方面的默认值，包括应用程序类型、默认包、测试框架、源语言、构建工具、GORM实现、servlet实现以及启用功能列表。

=== Grails默认包配置

项目的默认包是根据项目的名称确定的。例如，运行以下命令：

[source, shell]
----
grails create-app myapp
----

会将默认包设置为`myapp`。

如果您想要在创建应用程序时指定自己的默认包，可以通过在应用程序名称前添加包名来实现，例如：

[source, shell]
----
grails create-app com.example.myapp
----

在这种情况下，“com.example”将成为您项目的默认包。

=== Gradle构建工具

Grails现在使用Gradle构建系统进行项目管理。项目的构建配置在`build.gradle`文件中指定，您可以在其中定义项目的关键方面，例如版本、所需依赖项以及这些依赖项应该从哪些仓库获取。以下是如何完成的示例：

[source, groovy]
----
plugins {
    id 'org.grails.grails-web' version 'x.y.z' // Grails plugin
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.grails:grails-core'
    // 按需添加更多依赖项...
}

grails {
    pathingJar = true
}
----

=== 使用Gradle构建工具

要与您的Grails项目交互并执行与构建和运行相关的各种任务，您应该使用Gradle命令。以下是一些示例：

- 构建Grails应用程序：

[source, bash]
----
gradle build
----

- 运行Grails应用程序：

[source, bash]
----
gradle bootRun
----

- 列出可用的Gradle任务：

[source, bash]
----
gradle tasks
----

通过调用这些Gradle命令，您可以有效地管理您的Grails应用程序的生命周期。

重要的是要记住，Grails利用Gradle的强大功能来进行流畅的项目管理，包括构建自动化和依赖解析。这种方法允许您更灵活地控制您的Grails项目。