自动化测试是Grails开发的一个关键方面。Grails提供了丰富的测试功能，从低级单元测试到高级功能测试。这份详细的全面指南探讨了这些多样化的测试功能。

自动生成测试
当您使用 `create-*` 和 `generate-*` 命令时，Grails会自动生成 `unit` 或 `integration` 测试。例如，运行以下 `create-controller` 命令：

[source,shell]
----
grails create-controller com.example.simple
----

Grails会在grails-app/controllers/com/example/SimpleController.groovy生成一个控制器，同时在src/test/groovy/com/example/SimpleControllerSpec.groovy生成一个对应的单元测试。需要注意的是，Grails只会创建测试结构，您需要实现测试逻辑。

运行测试
要执行测试，您可以使用Gradle的 `check` 任务：

[source,shell]
----
./gradlew check
----

这个命令将执行src/main/groovy/com/example/目录中的所有单元测试。

目标测试
为了有选择地执行测试，您有几个选项：

1. 要运行名为SimpleController的所有控制器的测试，请使用以下命令：
+
[source,shell]
----
./gradlew check --tests SimpleController
----

2. 要测试所有以Controller结尾的类，可以使用通配符：
+
[source,shell]
----
./gradlew check --tests *Controller
----

3. 要指定包名：
+
[source,shell]
----
./gradlew check --tests some.org.*Controller
----

4. 要运行包中的所有测试：
+
[source,shell]
----
./gradlew check --tests some.org.*
----

5. 要运行包中的所有测试，包括子包：
+
[source,shell]
----
./gradlew check --tests some.org.**.*
----

6. 要定位特定测试方法：
+
[source,shell]
----
./gradlew check --tests SimpleController.testLogin
----

您可以根据需要组合多个模式。

注意：您可能需要在类名前指定包名并在其后添加"Spec"。例如，要运行ProductController的测试，请使用./gradlew test *.ProductControllerSpec。如果您想避免输入整个包层次结构，也可以使用星号通配符。

调试
要使用远程调试器调试您的测试，您可以在任何命令中的 `./gradlew` 后添加 `--debug-jvm` ，如下所示：

[source,shell]
----
./gradlew check --debug-jvm
----

这将打开默认的Java远程调试端口5005，允许您从代码编辑器或集成开发环境附加远程调试器。

定位测试阶段/分开运行单元和集成
要执行"unit"测试，使用以下命令：

[source,shell]
----
./gradlew test
----

对于"integration"测试，您可以运行：

[source,shell]
----
./gradlew integrationTest
----

在使用阶段时确定测试目标
您可以结合测试和阶段的定位：

[source,shell]
----
./gradlew test some.org.**.*
----

这个命令将在some.org包或其子包中的unit阶段运行所有测试。为了获得更为详细的信息，建议查阅 https://docs.gradle.org/current/userguide/java_testing.html[Java和JVM项目中的测试]的Gradle文档。