Grails支持动态编码/解码方法的概念。一组标准编解码器与Grails捆绑在一起。Grails还支持一个简单的机制，使开发人员能够在运行时贡献自己的编解码器，这些编解码器将在运行时被识别。

编解码器类
Grails编解码器类可能包含一个编码闭包、一个解码闭包或两者都有。当Grails应用程序启动时，Grails框架动态从`grails-app/utils/`目录加载编解码器。

该框架查找以`Codec`约定结尾的类名，位于`grails-app/utils/`下。例如，Grails附带的一个标准编解码器是`HTMLCodec`。

如果一个编解码器包含一个`encode`闭包，Grails将创建一个动态的`encode`方法，并将该方法添加到`Object`类中，方法的名称代表了定义了编码闭包的编解码器。例如，`HTMLCodec`类定义了一个`encode`闭包，所以Grails将其命名为`encodeAsHTML`。

`HTMLCodec`和`URLCodec`类还定义了一个`decode`闭包，因此Grails分别将其附加到名称为`decodeHTML`和`decodeURL`的方法上。动态编解码器方法可以在Grails应用程序的任何地方调用。例如，考虑一个情况，一个报告包含一个名为“description”的属性，该属性可能包含必须进行转义以在HTML文档中呈现的特殊字符。在GSP中处理这种情况的一种方法是使用下面显示的动态编码方法对描述属性进行编码：

[code,groovy]
----
${report.description.encodeAsHTML()}
----

解码使用`value.decodeHTML()`语法进行。

静态编译代码的编码器和解码器接口

使用编解码器的首选方法是使用codecLookup bean获取`Encoder`和`Decoder`实例。

[code,groovy]
----
package org.grails.encoder;

public interface CodecLookup {
    public Encoder lookupEncoder(String codecName);
    public Decoder lookupDecoder(String codecName);
}
----

使用`CodecLookup`和`Encoder`接口的示例
[code,groovy]
----
import org.grails.encoder.CodecLookup

class CustomTagLib {
    CodecLookup codecLookup

    def myTag = { Map attrs, body ->
        out << codecLookup.lookupEncoder('HTML').encode(attrs.something)
    }
}
----


标准编解码器

HTMLCodec
该编解码器执行HTML转义和反转义，以便值可以安全地在HTML页面中呈现，而不会创建任何HTML标记或损坏页面布局。例如，给定值“Don't you know that 2 > 1?”，您不能安全地显示在HTML页面中，因为`>将看起来关闭标签，如果您在属性中呈现这些数据，如输入字段的值属性尤其糟糕。

使用示例：

[code,groovy]
----
<input name="comment.message" value="${comment.message.encodeAsHTML()}"/>
----

注意：请注意，HTML编码不会重新对撇号/单引号进行编码，因此必须在属性值上使用双引号，以避免具有撇号的文本影响页面。

HTMLCodec默认为HTML4样式转义（在Grails 2.3.0之前的版本中的遗留HTMLCodec实现），可转义非ASCII字符。

您可以在`application.groovy`中设置此配置属性，而不是使用HTML4转义，而是使用纯XML转义：

[code,groovy]
----
grails.views.gsp.htmlcodec = 'xml'
----

XMLCodec
该编解码器执行XML转义和反转义。它转义 & , < , > , " , ', \ ， @ ， ` ，不间断空格（\u00a0），行分隔符（\u2028）和段分隔符（\u2029）。

HTMLJSCodec
该编解码器执行HTML和JS编码。用于防止某些DOM-XSS漏洞。请参阅[OWASP - DOM based XSS Prevention Cheat Sheet]以了解如何预防基于DOM的XSS攻击的准则。

URLCodec
在创建链接或表单操作链接时，或任何时候数据用于创建URL时，需要进行URL编码。它防止非法字符进入URL并改变其含义，例如“Apple & Blackberry”作为GET请求中的参数不会很好地工作，因为和符号将破坏参数解析。

使用示例：

[code,groovy]