==== 创建插件

创建一个Grails插件只需要运行以下命令:

[source,groovy]
----
grails create-plugin <<PLUGIN NAME>>
----

这将为您指定的名称创建一个web插件项目。例如，运行 `grails create-plugin example` 将创建一个名为 `example` 的新web插件项目。

在Grails 3.0中，您应该考虑您创建的插件是否需要一个web环境，或者插件是否可以与其他配置文件一起使用。如果您的插件不需要web环境，则应该使用“plugin”配置文件而不是默认的“web-plugin”配置文件:

[source,groovy]
----
grails create-plugin <<PLUGIN NAME>> --profile=plugin
----

请确保插件名称不包含超过一个大写字母，否则将无法使用。但是，驼峰命名法是可以的。

作为常规的Grails项目，有许多好处，因为您可以立即通过运行来测试您的插件（如果插件针对“web”配置文件）:

[source,shell]
----
./gradlew bootRun
----

注意: 默认情况下，插件项目不提供index.gsp文件，因为大多数插件不需要。因此，如果您在创建插件后立即尝试在浏览器中查看插件运行，您将收到一个页面未找到的错误。 如果您愿意，您可以轻松创建一个 `grails-app/views/index.gsp` 来为您的插件创建。

Grails插件的结构几乎与Grails应用程序项目的结构相同，只是在插件包结构下的 `src/main/groovy` 目录下会找到一个插件描述符类（一个以“GrailsPlugin”结尾的类）。例如:

[source,groovy]
----
import grails.plugins.*

class ExampleGrailsPlugin extends Plugin {
   ...
}
----

所有插件都必须在 `src/main/groovy` 目录下拥有这个类，否则它们将不被视为插件。插件类定义了关于插件的元数据，以及可选的插件扩展点。

您还可以使用几个特殊属性提供有关您的插件的其他信息:

* `title` - 插件的简短一句描述
* `grailsVersion` - 插件支持的Grails版本范围。例如“1.2 > *”（表示1.2或更高版本）
* `author` - 插件作者的姓名
* `authorEmail` - 插件作者的联系邮箱
* `developers` - 除上面指定的作者之外的任何额外开发人员
* `description` - 插件功能的完整多行描述
* `documentation` - 插件文档的URL
* `license` - 插件的许可证
* `issueManagement` - 插件的问题跟踪
* `scm` - 插件的源代码管理位置

以下是 https://github.com/grails-plugins/grails-quartz[Quartz Grails插件]的一个简化示例:

[source,groovy]
----
package quartz

@Slf4j
class QuartzGrailsPlugin extends Plugin {
    // 插件设计的Grails版本或版本
    def grailsVersion = "3.0.0.BUILD-SNAPSHOT > *"
    // 插件打包中被排除的资源
    def pluginExcludes = [
            "grails-app/views/error.gsp"
    ]
    def title = "Quartz" // 插件的主题显示名称
    def author = "Jeff Brown"
    def authorEmail = "zzz@yyy.com"
    def description = '''\
Adds Quartz job scheduling features
'''
    def profiles = ['web']
    List loadAfter = ['hibernate3', 'hibernate4', 'hibernate5', 'services']
    def documentation = "http://grails.org/plugin/quartz"
    def license = "APACHE"
    def issueManagement = [ system: "Github Issues", url: "http://github.com/grails3-plugins/quartz/issues" ]
    def developers = [
            [ name: "Joe Dev", email: "joedev@gmail.com" ]
    ]
    def scm = [ url: "https://github.com/grails3-plugins/quartz/" ]

    Closure doWithSpring()......
----

==== 插件配置

与其直接访问Grails配置，例如 `grailsApplication.config.getProperty('mail.hostName', String)` ，我们可以使用一个带有 {springbootapi}/org/springframework/boot/context/properties/ConfigurationProperties.html[ConfigurationProperties]注解的Spring Boot配置bean（或POJO）。以下是一个插件配置示例:

_./src/main/groovy/example/MailPluginConfiguration.groovy_
[source,groovy]
```
package example

import org.springframework.boot.context.properties.ConfigurationProperties

@ConfigurationProperties(prefix = "mail")
class MailPluginConfiguration {

    String hostName
    int port
    String from
}

```

您可以像任何其他bean一样将 `MailPluginConfiguration` 注入到您的bean中。

_./grails-app/services/example/MailService.groovy_
[source,groovy]
```
package example

class MailService {

    MailPluginConfiguration mailPluginConfiguration

    void sendMail() {

    }

}

```

请阅读 {springBootReference}/html/features.html#features.external-config[Spring Boot Externalized Configuration]部分获取更多信息。

==== 安装本地插件

为了将Grails插件安装到您本地的Maven中，您可以使用Gradle https://docs.gradle.org/current/userguide/publishing_maven.html[Maven Publish]插件。您还可能需要配置发布扩展如下:

[source,groovy]
----
publishing {
    publications {
        maven(MavenPublication) {
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            from components.java
        }
    }
}
----

注意：请参考Gradle Maven Publish插件文档获取最新信息。

要使您的插件可用于Grails应用程序中，请运行 `./gradlew publishToMavenLocal` 命令:

[source,bash]
----
./gradlew publishToMavenLocal
----

这将安装插件到您本地的Maven缓存中。然后，在应用程序中声明对插件的依赖项，在您的 `build.gradle` 文件中包含 `mavenLocal()` 在您的repositories哈希中:

[source,groovy]
----
...
repositories {
    ...
    mavenLocal()
}
...
implementation "org.grails.plugins:quartz:0.1"
----

注意：在Grails 2.x中，插件打包为ZIP文件，然而在Grails 3.x中，插件是简单的JAR文件，可以添加到IDE的类路径中。

==== 插件和多项目构建

如果您希望将插件设置为多项目构建的一部分，请按照以下步骤操作。

*步骤1: 创建应用程序和插件*

使用 `grails` 命令创建一个应用程序和一个插件:

[source,groovy]
----
$ grails create-app myapp
$ grails create-plugin myplugin
----

*步骤2: 创建一个settings.gradle文件*

在相同目录中创建一个 `settings.gradle` 文件，其中包含以下内容:

[source,groovy]
----
include "myapp", "myplugin"
----

目录结构应如下所示:

[source,groovy]
----
项目目录
  - settings.gradle
  - myapp
    - build.gradle
  - myplugin
    - build.gradle
----

*步骤3: 在插件中声明对该插件的项目依赖*

在应用程序的 `build.gradle` 中，在 `plugins` 块内声明对插件的依赖关系:

[source,groovy]
----
grails {
    plugins {
        implementation project(':myplugin')
    }
}
----

注意: 您也可以在 `dependencies` 块内声明依赖关系，但是这样做将不会获得子项目重新加载！

*步骤4: 配置插件以启用重新加载*

在插件目录中，添加或修改 `gradle.properties` 文件。需要设置一个新属性 `exploded=true` ，以便插件将爆炸目录添加到类路径中。

*步骤5: 运行应用程序*

现在从应用程序目录的根目录使用 `./gradlew bootRun` 命令运行应用程序，您可以使用 `verbose` 标志查看Gradle输出:

[source,groovy]
----
$ cd myapp
$ ./gradlew bootRun --verbose
----

您将从Gradle输出中注意到插件源代码已构建并放置在应用程序的类路径上。