控制插件依赖关系

插件经常依赖于其他插件的存在，并且可以根据其他插件的存在进行调整。这是通过两种属性实现的。第一个称为 `dependsOn` 。例如，看一下Hibernate插件中的这个片段：

[source,groovy]
----
class HibernateGrailsPlugin {

    def version = "1.0"

    def dependsOn = [dataSource: "1.0",
                     domainClass: "1.0",
                     i18n: "1.0",
                     core: "1.0"]
}
----

Hibernate插件依赖于四个插件的存在： `dataSource` ， `domainClass` ， `i18n` 和 `core` 插件。

依赖关系将在Hibernate插件之前加载，如果所有依赖项没有加载，则插件将不会加载。

`dependsOn` 属性还支持用于指定版本范围的迷你表达式语言。以下是一些语法示例：

[source,groovy]
----
def dependsOn = [foo: "* > 1.0"]
def dependsOn = [foo: "1.0 > 1.1"]
def dependsOn = [foo: "1.0 > *"]
----

当使用通配符*字符时，它表示“任何”版本。表达式语法还排除任何后缀，如-BETA，-ALPHA等，因此例如表达式“1.0 > 1.1”将匹配以下任何版本：

* 1.1
* 1.0
* 1.0.1
* 1.0.3-SNAPSHOT
* 1.1-BETA2

控制加载顺序

使用 `dependsOn` 建立了一个“硬”依赖，如果依赖关系没有解析，插件将放弃并不会加载。但是也可以使用 `loadAfter` 和 `loadBefore` 属性实现弱依赖：

[source,groovy]
----
def loadAfter = ['controllers']
----

在这里，如果 `controllers` 插件存在，则该插件将在 `controllers` 插件之后加载，否则将仅加载。然后插件可以根据其他插件的存在进行调整，例如Hibernate插件在其 `doWithSpring` 闭包中有以下代码：

[source,groovy]
----
if (manager?.hasGrailsPlugin("controllers")) {
    openSessionInViewInterceptor(OpenSessionInViewInterceptor) {
        flushMode = HibernateAccessor.FLUSH_MANUAL
        sessionFactory = sessionFactory
    }
    grailsUrlHandlerMapping.interceptors << openSessionInViewInterceptor
}
----

在这里，只有在加载 `controllers` 插件后，Hibernate插件才会注册 `OpenSessionInViewInterceptor` 。 `manager` 变量是{apiDocs}grails/plugins/GrailsPluginManager.html[GrailsPluginManager]接口的一个实例，它提供了与其他插件交互的方法。

您还可以使用 `loadBefore` 属性指定应在您的插件之前加载的一个或多个插件：

[source,groovy]
----
def loadBefore = ['rabbitmq']
----