这个Grails中的Bean构建器旨在提供一种简化的方法，用于将使用Spring作为核心的依赖项进行连线。

此外，Spring的常规配置方式（通过XML和注解）是静态的，很难在运行时进行修改和配置，除非是通过编程方式创建XML，但这既容易出错又啰嗦。Grails的BeanBuilder通过在运行时将组件以编程方式连接起来，使您能够根据系统属性或环境变量调整逻辑，从而改变这一切。

这使得代码能够适应其环境，避免代码不必要的重复（为测试、开发和生产环境设置不同的Spring配置）。

BeanBuilder类

Grails提供了一个使用动态Groovy构建Bean定义的grails.spring.BeanBuilder类。基本原理如下：

[source,groovy]
----
import org.apache.commons.dbcp.BasicDataSource
import org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean
import org.springframework.context.ApplicationContext
import grails.spring.BeanBuilder

def bb = new BeanBuilder()

bb.beans {

    dataSource(BasicDataSource) {
        driverClassName = "org.h2.Driver"
        url = "jdbc:h2:mem:grailsDB"
        username = "sa"
        password = ""
    }

    sessionFactory(ConfigurableLocalSessionFactoryBean) {
        dataSource = ref('dataSource')
        hibernateProperties = ["hibernate.hbm2ddl.auto": "create-drop",
                               "hibernate.show_sql": "true"]
    }
}

ApplicationContext appContext = bb.createApplicationContext()
----

注意：在 link:plugins.html[插件]和 `grails-app/conf/spring/resources.groovy` 文件中，您不需要创建一个新的 `BeanBuilder` 的实例。相反，DSL分别在 `doWithSpring` 和 `beans` 块中隐式可用。

此示例显示了如何使用BeanBuilder类配置带有数据源的Hibernate。

每个方法调用（在这种情况下是 `dataSource` 和 `sessionFactory` 调用）映射到Spring中Bean的名称。方法的第一个参数是Bean的类，而最后一个参数是一个块。在块的主体中，您可以使用标准的Groovy语法为Bean设置属性。

Bean引用会自动根据Bean的名称解析。在上面的示例中可以看到 `sessionFactory` bean 是如何解析 `dataSource` 引用的。

构建器还可以设置与Bean管理相关的特殊属性，如下所示：

[source,groovy]
----
sessionFactory(ConfigurableLocalSessionFactoryBean) { bean ->
    // 自动装配行为。另一个选项是'byType'。 <<autowire>>
    bean.autowire = 'byName'
    // 将初始化方法设置为'init'。 [init-method]
    bean.initMethod = 'init'
    // 将销毁方法设置为'destroy'。 [destroy-method]
    bean.destroyMethod = 'destroy'
    // 设置Bean的范围。 <<scope>>
    bean.scope = 'request'
    dataSource = ref('dataSource')
    hibernateProperties = ["hibernate.hbm2ddl.auto": "create-drop",
                           "hibernate.show_sql": "true"]
}
----

方括号中的字符串是Spring XML定义中等效Bean属性的名称。

使用BeanBuilder与Spring MVC

在常规的Spring MVC应用程序中，需要在类路径中包含 `grails-spring-<version>.jar` 文件才能使用BeanBuilder。然后，将以下 `<context-param>` 值添加到 `/WEB-INF/web.xml` 文件中：

[source, xml]
----
<context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>/WEB-INF/applicationContext.groovy</param-value>
</context-param>

<context-param>
    <param-name>contextClass</param-name>
    <param-value>
      grails.web.servlet.context.GrailsWebApplicationContext
    </param-value>
</context-param>
----

然后创建一个 `/WEB-INF/applicationContext.groovy` 文件执行剩下的操作：

[source, groovy]
----
import org.apache.commons.dbcp.BasicDataSource

beans {
    dataSource(BasicDataSource) {
        driverClassName = "org.h2.Driver"
        url = "jdbc:h2:mem:grailsDB"
        username = "sa"
        password = ""
    }
}
----

从文件系统加载Bean定义

您可以使用 `BeanBuilder` 类加载外部Groovy脚本，这些脚本使用与此处定义的相同的路径匹配语法来定义Bean。例如：

[source,groovy]
----
def bb = new BeanBuilder()
bb.loadBeans("classpath:*SpringBeans.groovy")

def applicationContext = bb.createApplicationContext()
----

这里的 `BeanBuilder` 加载类路径上以 `SpringBeans.groovy` 结尾的所有Groovy文件，并将它们解析为Bean定义。下面是一个示例脚本：

[source, groovy]
----
import org.apache.commons.dbcp.BasicDataSource
import org.grails.orm.hibernate.ConfigurableLocalSessionFactoryBean

beans {

    dataSource(BasicDataSource) {
        driverClassName = "org.h2.Driver"
        url = "jdbc:h2:mem:grailsDB"
        username = "sa"
        password = ""
    }

    sessionFactory(ConfigurableLocalSessionFactoryBean) {
        dataSource = dataSource
        hibernateProperties = ["hibernate.hbm2ddl.auto": "create-drop",
                               "hibernate.show_sql": "true"]
    }
}
----

向绑定（上下文）添加变量

如果您从脚本中加载Bean，可以通过创建一个Groovy `Binding` 来设置要使用的绑定：

[source,groovy]
----
def binding = new Binding()
binding.maxSize = 10000
binding.productGroup = 'finance'

def bb = new BeanBuilder()
bb.binding = binding
bb.loadBeans("classpath:*SpringBeans.groovy")

def ctx = bb.createApplicationContext()
----

然后您可以在DSL文件中访问 `maxSize` 和 `productGroup` 属性。