在Grails中常见的模式是使用链接:theWebLayer.html#commandObjects[命令对象]来验证用户提交的数据，然后将命令对象的属性复制到相关的领域类中。这通常意味着您的命令对象和领域类共享属性和它们的约束。您可以手动在两者之间复制和粘贴约束，但这是一种非常容易出错的方法。相反，利用Grails的全局约束和导入机制。

全局约束

除了在领域类、命令对象和<<validationNonDomainAndCommandObjectClasses,其他可验证类>>中定义约束外，您还可以在 `grails-app/conf/runtime.groovy` 中定义它们：

[source,groovy]
----
grails.gorm.default.constraints = {
    '*'(nullable: true, size: 1..20)
    myShared(nullable: false, blank: false)
}
----

这些约束没有附加到任何特定的类，但可以很容易地从任何可验证类中引用：

[source,groovy]
----
class User {
    ...

    static constraints = {
        login shared: "myShared"
    }
}
----

请注意使用 `shared` 参数，其值是在 `grails.gorm.default.constraints` 中定义的约束之一的名称。尽管配置设置的名称是这样的，您可以从任何可验证类引用这些共享约束，例如命令对象。

'*'约束是一个特殊情况：它意味着关联的约束（上面示例中的'nullable'和'size'）将应用于所有可验证类中的所有属性。这些默认值可以被可验证类中声明的约束覆盖。

导入约束

Grails 2引入了一种替代的共享约束方法，允许您将一个类中的一组约束导入到另一个类中。

假设您有一个领域类如下：

[source,groovy]
----
class User {
    String firstName
    String lastName
    String passwordHash

    static constraints = {
        firstName blank: false, nullable: false
        lastName blank: false, nullable: false
        passwordHash blank: false, nullable: false
    }
}
----

然后您想要创建一个命令对象 `UserCommand` ，它共享领域类的一些属性和相应的约束。您可以使用 `importFrom()` 方法来做到这一点：

[source,groovy]
----
class UserCommand {
    String firstName
    String lastName
    String password
    String confirmPassword

    static constraints = {
        importFrom User

        password blank: false, nullable: false
        confirmPassword blank: false, nullable: false
    }
}
----

这将从 `User` 领域类导入所有约束，并将它们应用于 `UserCommand` 。导入将忽略源类（ `User` ）中没有相应属性的任何约束，而不会应用到导入类（ `UserCommand` ）中。在上面的示例中，只有 'firstName' 和 'lastName' 的约束将被导入到 `UserCommand` 中，因为这两个类共享的唯一属性。

如果您想要更多控制哪些约束被导入，可以使用 `include` 和 `exclude` 参数。这两个参数接受一个简单或正则表达式字符串列表，匹配源约束中的属性名称。例如，如果您只想导入 'lastName' 的约束，您可以使用：

[source,groovy]
----
...
static constraints = {
    importFrom User, include: ["lastName"]
    ...
}
----

或者如果您想要导入所有以 'Name' 结尾的约束：

[source,groovy]
----
...
static constraints = {
    importFrom User, include: [/.*Name/]
    ...
}
----

当然， `exclude` 则做相反的操作，指定不应该导入哪些约束。