### 升级 Grails 版本

你需要升级 `gradle.properties` 中定义的 Grails 版本。

Grails 3 应用的 `gradle.properties`

[source, properties]
.gradle.properties
----
...
grailsVersion=3.3.8
...
----

Grails 4 应用的 `gradle.properties`

[source, groovy, subs="attributes"]
.gradle.properties
----
...
grailsVersion=4.0.4
...
----

### 升级 GORM 版本

如果你使用了 http://gorm.grails.org[GORM]，你需要更新 `gradle.properties` 中定义的版本。

Grails 3 应用的 `gradle.properties`

[source, properties]
.gradle.properties
----
...
gormVersion=6.1.10.RELEASE
...
----

Grails 4 应用的 `gradle.properties`

[source, properties]
.gradle.properties
----
...
gormVersion=7.0.4
...
----

### 将 GORM DSL 条目移到 runtime.groovy

GORM DSL 条目应该移到 `runtime.groovy`。例如，在 `application.groovy` 中使用以下 GORM 配置是不受支持的，会导致应用程序崩溃：

[source, groovy]
----
grails.gorm.default.mapping = {
    id generator: 'identity'
}
----

### Spring 5 和 Spring Boot 2.1

Grails 4.0 是基于 Spring 5 和 Spring Boot 2.1 构建的。如果你使用了 Spring 特定功能，请查看迁移指南和发布说明。

### Hibernate 5.4 和 GORM 7.x

Grails 4.x 支持 Hibernate 5.4 和 GORM 7.x 的最低版本。为了支持更新版本的 Hibernate 并简化 GORM 本身，已经做了几个更改。

有关这些更改的详细信息请参阅 GORM 升级文档。

### Spring Boot 2.1 执行器

请查阅 Spring Boot 执行器文档，因为与 Grails 3.x 使用的版本相比，它已经发生了重大变化。

如果你有以下配置：

[source, yml]
.grails-app/conf/application.yml - Grails 3.3.x
----
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true
----

请将其替换为：

[source, yml]
.grails-app/conf/application.yml - Grails 4.x
----
spring:
    jmx:
        unique-names: true
management:
    endpoints:
        enabled-by-default: false
----

### Spring Boot 开发者工具和 Spring Loaded

之前的 Grails 版本使用了一个叫做 Spring Loaded 的重载代理。由于该库不再维护，并且不支持 Java 11，因此已经删除了对 Spring Loaded 的支持。

作为替代，Grails 4 应用程序在 `build.gradle` 构建脚本中包含了 Spring Boot 开发者工具的依赖项。如果你要迁移一个 Grails 3.x 应用程序，请包含以下一组依赖项：

[source, groovy]
.build.gradle
----
.
..
...
configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

dependencies {
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	...
	..
}
...
..
.
----

此外，你应该在 `application.yml` 中为 Spring 开发者工具配置必要的排除项：

[source,yaml]
----
spring:
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**
----

上述配置可以防止在更改视图或消息束时重新启动服务器。

注意：你可以使用 Spring 开发者工具与浏览器扩展（例如 Chrome 的 LiveReload 扩展）结合使用，以在更改 Grails 应用程序中的任何内容时自动刷新浏览器。

### Spring Boot Gradle 插件更改

Grails 4 是基于 Spring Boot 2.1 构建的。Grails 3 应用程序是基于 Spring Boot 1.x 构建的。

你的 Grails 3 应用程序的 `build.gradle` 可能有这样的配置：

[source, groovy]
.build.gradle
----
bootRun {
    addResources = true
    ...
}
----

Grails 4 应用程序是基于 Spring Boot 2.1 构建的。从 Spring Boot 2.0 开始，`addResources` 属性不再存在。相反，你需要将 `sourceResources` 属性设置为你想要使用的源集。通常是 `sourceSets.main`。这在 Spring Boot Gradle 插件文档中有描述。

你的 Grails 4 应用程序的 `build.gradle` 可以配置为：

[source, groovy]
.build.gradle
----
bootRun {
	sourceResources sourceSets.main
    ...
}
----


### 为 Grails 插件构建可执行的 JAR 包

Spring Boot 2.1 包含了对 H2 数据库 Web 控制台的原生支持。由于这已经包含在 Spring Boot 中，因此相应的功能已从 Grails 中移除。因此，H2 控制台现在可用于 `/h2-console`，而不是之前的 `/dbconsole`。有关更多信息，请参阅 Spring Boot 文档中关于使用 H2 Web 控制台的部分。

### 升级 Hibernate

如果你在 Grails 3 应用程序中使用 GORM 来实现 Hibernate，你需要升级到 Hibernate 5.4。

类似于以下的 Grails 3 `build.gradle`：

[source, groovy]
.build.gradle
----
dependencies {
...
  implementation "org.grails.plugins:hibernate5"
  implementation "org.hibernate:hibernate-core:5.1.5.Final"
}
----

将在 Grails 4 中变为：

[source, groovy]
.build.gradle
----
dependencies {
...
  implementation "org.grails.plugins:hibernate5"
  implementation "org.hibernate:hibernate-core:5.4.0.Final"
}
----


### 迁移到 Geb 2.3

Geb 1.1.x（与 JDK 1.7 兼容的版本）是 Grails 3 默认附带的版本。Grails 4 不再与 Java 1.7 兼容。你应该迁移到 Geb 2.3。

在 Grails 3 中，如果你的 build.gradle 如下所示：

[source, groovy]
.build.gradle
----
dependencies {
 testCompile "org.grails.plugins:geb:1.1.2"
 testRuntime "org.seleniumhq.selenium:selenium-htmlunit-driver:2.47.1"
 testRuntime "net.sourceforge.htmlunit:htmlunit:2.18"
}
----

在 Grails 4 中，你应该将其替换为：

[source, groovy]
.build.gradle
----
buildscript {
    repositories {
       ...
    }
    dependencies {
        ...
        classpath "gradle.plugin.com.energizedwork.webdriver-binaries:webdriver-binaries-gradle-plugin:$webdriverBinariesVersion" // <1>
    }
}
...
..

repositories {
  ...
}

apply plugin:"idea"
...
...
apply plugin:"com.energizedwork.webdriver-binaries" // <1>


dependencies {
...
    testCompile "org.grails.plugins:geb" // <4>
    testRuntime "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"  // <5>
    testRuntime "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion" // <5>
    testRuntime "org.seleniumhq.selenium:selenium-safari-driver:$seleniumSafariDriverVersion" // <5>

    testCompile "org.seleniumhq.selenium:selenium-remote-driver:$seleniumVersion" // <5>
    testCompile "org.seleniumhq.selenium:selenium-api:$seleniumVersion" // <5>
    testCompile "org.seleniumhq.selenium:selenium-support:$seleniumVersion" // <5>
}

webdriverBinaries {
    chromedriver "$chromeDriverVersion" // <2>
    geckodriver "$geckodriverVersion" // <3>
}

tasks.withType(Test) {
    systemProperty "geb.env", System.getProperty('geb.env')
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")
    systemProperty "webdriver.chrome.driver", System.getProperty('webdriver.chrome.driver')
    systemProperty "webdriver.gecko.driver", System.getProperty('webdriver.gecko.driver')
}
----

[source,properties]
.gradle.properties
----
gebVersion=2.3
seleniumVersion=3.12.0
webdriverBinariesVersion=1.4
hibernateCoreVersion=5.1.5.Final
chromeDriverVersion=2.44 // <2>
geckodriverVersion=0.23.0 // <3>
seleniumSafariDriverVersion=3.14.0
----

<1> 包含 https://plugins.gradle.org/plugin/com.energizedwork.webdriver-binaries[Webdriver binaries Gradle plugin]。
<2> 设置适当的 http://chromedriver.chromium.org[Chrome 版本的 Webdriver]。
<3> 设置适当的 https://github.com/mozilla/geckodriver/releases[Firefox 版本的 Webdriver]。
<4> 包括 https://github.com/grails3-plugins/geb[Grails Geb Plugin 依赖项]，它具有对 `geb-spock` 的传递依赖。这是与 Geb 和 Spock 一起使用所必需的依赖项。
<5> Selenium 和不同的驱动程序依赖项。

还要在 `src/integration-test/resources/GebConfig.groovy` 中创建 http://www.gebish.org/manual/current/#configuration[Geb 配置] 文件。

[source, groovy]
.src/integration-test/resources/GebConfig.groovy
----
import org.openqa.selenium.chrome.ChromeDriver
import org.openqa.selenium.chrome.ChromeOptions
import org.openqa.selenium.firefox.FirefoxDriver
import org.openqa.selenium.firefox.FirefoxOptions
import org.openqa.selenium.safari.SafariDriver

environments {

    // You need to configure in Safari -> Develop -> Allowed Remote Automation
    safari {
        driver = { new SafariDriver() }
    }

    // run via “./gradlew -Dgeb.env=chrome iT”
    chrome {
        driver = { new ChromeDriver() }
    }

    // run via “./gradlew -Dgeb.env=chromeHeadless iT”
    chromeHeadless {
        driver = {
            ChromeOptions o = new ChromeOptions()
            o.addArguments('headless')
            new ChromeDriver(o)
        }
    }

    // run via “./gradlew -Dgeb.env=firefoxHeadless iT”
    firefoxHeadless {
        driver = {
            FirefoxOptions o = new FirefoxOptions()
            o.addArguments('-headless')
            new FirefoxDriver(o)
        }
    }

    // run via “./gradlew -Dgeb.env=firefox iT”
    firefox {
        driver = { new FirefoxDriver() }
    }
}
----



### 已弃用的类


以下在 Grails 3.x 中已弃用的类在 Grails 4 中已被移除。请检查以下列表，找到适当的替代方案：

|===
| 已移除的类 | 替代方案
| `org.grails.datastore.gorm.validation.constraints.UniqueConstraint` |
`org.grails.datastore.gorm.validation.constraints.builtin.UniqueConstraint`
| `grails.util.BuildScope` |
| `grails.transaction.GrailsTransactionTemplate` | `grails.gorm.transactions.GrailsTransactionTemplate`
| `org.grails.transaction.transform.RollbackTransform` | `org.grails.datastore.gorm.transactions.transform.RollbackTransform`
| `grails.transaction.NotTransactional` | `grails.gorm.transactions.NotTransactional`
| `grails.transaction.Rollback` | `grails.gorm.transactions.Rollback`
| `grails.transaction.Transactional` | `grails.gorm.transactions.Transactional`
| `org.grails.config.FlatConfig` |
| `org.grails.core.metaclass.MetaClassEnhancer` | 使用 traits 替代。
| `org.grails.core.util.ClassPropertyFetcher` | `org.grails.datastore.mapping.reflect.ClassPropertyFetcher`
| `org.grails.transaction.transform.TransactionalTransform` | `org.grails.datastore.gorm.transactions.transform.TransactionalTransform`
| `grails.core.ComponentCapableDomainClass` |
| `grails.core.GrailsDomainClassProperty` | 使用 `org.grails.datastore.mapping.model.MappingContext` API。
| `org.grails.core.DefaultGrailsDomainClassProperty` |
| `org.grails.core.MetaGrailsDomainClassProperty` |
| `org.grails.core.support.GrailsDomainConfigurationUtil` | 使用 `org.grails.datastore.mapping.model.MappingContext` 和 `org.grails.datastore.mapping.model.MappingFactory` APIs。
| `org.grails.plugins.domain.DomainClassPluginSupport` |
| `org.grails.plugins.domain.support.GormApiSupport` |
| `org.grails.plugins.domain.support.GrailsDomainClassCleaner` | 现在由 `org.grails.datastore.mapping.model.MappingContext` 处理。
| `grails.validation.AbstractConstraint` | 使用 `org.grails.datastore.gorm.validation.constraints.AbstractConstraint`。
| `grails.validation.AbstractVetoingConstraint` | `org.grails.datastore.gorm.validation.constraints.AbstractVetoingConstraint`
| `grails.validation.CascadingValidator` | `grails.gorm.validation.CascadingValidator`
| `grails.validation.ConstrainedProperty` | `grails.gorm.validation.ConstrainedProperty`
| `grails.validation.Constraint` | `grails.gorm.validation.Constraint`
| `grails.validation.ConstraintFactory` | `org.grails.datastore.gorm.validation.constraints.factory.ConstraintFactory`
| `grails.validation.VetoingConstraint` | `grails.gorm.validation.VetoingConstraint`
| `grails.validation.ConstraintException` |
| `org.grails.validation.BlankConstraint` | `org.grails.datastore.gorm.validation.constraints.BlankConstraint`
| `org.grails.validation.ConstrainedPropertyBuilder` | `org.grails.datastore.gorm.validation.constraints.builder.ConstrainedPropertyBuilder`
| `org.grails.validation.ConstraintDelegate` |
| `org.grails.validation.ConstraintsEvaluatorFactoryBean` | `org.grails.datastore.gorm.validation.constraints.eval.ConstraintsEvaluator`
| `org.grails.validation.CreditCardConstraint` | `org.grails.datastore.gorm.validation.constraints.CreditCardConstraint`
| `org.grails.validation.DefaultConstraintEvaluator` | `org.grails.datastore.gorm.validation.constraints.eval.DefaultConstraintEvaluator`
| `org.grails.validation.DomainClassPropertyComparator` |
| `org.grails.validation.EmailConstraint` | `org.grails.datastore.gorm.validation.constraints.EmailConstraint`
| `org.grails.validation.GrailsDomainClassValidator` | `grails.gorm.validation.PersistentEntityValidator`
| `org.grails.validation.InListConstraint` | `org.grails.datastore.gorm.validation.constraints.InListConstraint`
| `org.grails.validation.MatchesConstraint` | `org.grails.datastore.gorm.validation.constraints.MatchesConstraint`
| `org.grails.validation.MaxConstraint` | `org.grails.datastore.gorm.validation.constraints.MaxConstraint`
| `org.grails.validation.MaxSizeConstraint` | `org.grails.datastore.gorm.validation.constraints.MaxSizeConstraint`
| `org.grails.validation.MinConstraint` | `org.grails.datastore.gorm.validation.constraints.MinConstraint`
| `org.grails.validation.MinSizeConstraint` | `org.grails.datastore.gorm.validation.constraints.MinSizeConstraint`
| `org.grails.validation.NotEqualConstraint` | `org.grails.datastore.gorm.validation.constraints.NotEqualConstraint`
| `org.grails.validation.NullableConstraint` | `org.grails.datastore.gorm.validation.constraints.NullableConstraint`
| `org.grails.validation.RangeConstraint` | `org.grails.datastore.gorm.validation.constraints.RangeConstraint`
| `org.grails.validation.ScaleConstraint` | `org.grails.datastore.gorm.validation.constraints.ScaleConstraint`
| `org.grails.validation.SizeConstraint` | `org.grails.datastore.gorm.validation.constraints.SizeConstraint`
| `org.grails.validation.UrlConstraint` | `org.grails.datastore.gorm.validation.constraints.UrlConstraint`
| `org.grails.validation.ValidatorConstraint` | `org.grails.datastore.gorm.validation.constraints.ValidatorConstraint`
| `org.grails.validation.routines.DomainValidator` | 使用更新的 commons-validation 版本
| `org.grails.validation.routines.InetAddressValidator` | 使用更新的 commons-validation 版本
| `org.grails.validation.routines.RegexValidator` | 使用更新的 commons-validation 版本
| `org.grails.validation.routines.ResultPair` | 使用更新的 commons-validation 版本
| `org.grails.validation.routines.UrlValidator` | 使用更新的 commons-validation 版本
| `grails.web.JSONBuilder`| `groovy.json.StreamingJsonBuilder`
|===

### Grails-Java8

如果您已添加依赖于 `grails-java8` 插件，则只需删除该依赖即可。插件中的所有类都已移出到各自的项目中。

### Profiles Deprecation

在 Grails 3.x 中支持的一些配置文件将不再继续维护，因此在缩写形式中创建应用程序将不再可能。在升级现有项目时，必须为这些配置文件提供版本号。

* `org.grails.profiles:angularjs` -> `org.grails.profiles:angularjs:1.1.2`
* `org.grails.profiles:webpack` -> `org.grails.profiles:webpack:1.1.6`
* `org.grails.profiles:react-webpack` -> `org.grails.profiles:react-webpack:1.0.8`

### Scheduled Methods

在 Grails 3 中，要使用 Spring 的 `@Scheduled` 注解，不需要任何配置或额外的更改。在 Grails 4 中，您必须在应用程序类中应用 `@EnableScheduling` 注解，以使调度工作。
