### 升级 Grails 版本

您需要升级 `gradle.properties` 中定义的 Grails 版本如下：

[source,groovy,subs="attributes"]
.gradle.properties
----
...
grailsVersion=5.2.0
...
----

### Apache Groovy 3.0.7

Grails 5.1.1 提供了对 Groovy 3 的支持。我们建议您查看 https://groovy-lang.org/releasenotes/groovy-3.0.html[Groovy 3 的发布说明]，以更新您的应用程序，以防您使用的特定功能在 Groovy 3 中不起作用。

在 `gradle.properties` 中定义 groovyVersion 强制应用程序使用 Groovy 3。

Grails 5.1 应用程序的 `gradle.properties`

[source, properties]
.gradle.properties
----
...
groovyVersion=3.0.7
...
----

### 升级 GORM 版本

如果您使用了 GORM，请将 `gradle.properties` 中定义的版本更新为：

[source, properties]
.gradle.properties
----
...
gormVersion=7.2.0
...
----

### 升级 gradle 版本

Grails 5.2.x 使用 gradle 7.2

[source, properties]
.gradle-wrapper.properties
----
...
distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip
...
----

您也可以运行以下命令

[source, properties]
----
./gradlew wrapper --gradle-version 7.2
----

### GORM for MonogDB 同步驱动

GORM for MongoDB 已更新以支持最新的 mongodb-driver-sync。如果您正在使用 GORM for MongoDB 并对 MongoDB 驱动程序或低级别 Mongo API 进行了特定操作，则可能需要查看 https://mongodb.github.io/mongo-java-driver/4.0/upgrading/[升级至 4.0 驱动程序]。

### 升级 Asset Pipeline 插件版本

之前的 asset-pipeline 版本不支持 Grails 5.0，因为它是使用与 Groovy 3 不兼容的版本编译的。因此，请将插件版本更新为 3.2.4。

### 默认禁用 StringCharArrayAccessor

之前的 Grails 版本使用 `StringCharArrayAccessor` ，默认启用并提供对 `java.lang.String` 内部的优化访问。在 Grails 5.0 中，默认情况下已禁用它，但您可以通过设置一个名为 `stringchararrayaccessor.disabled` 的系统属性并将其值设置为 `false` 来启用它。

注意：启用 StringCharArrayAccessor 将显示非法反射访问警告，因为它使用反射来进行优化。

### Grails Profiles 中 profile.yml 和 feature.yml 文件的更改

定义依赖项的方式在功能和配置文件中的更改了。有关更多信息，请参阅 link:profiles.html[Application Profiles] 章节。

### Grails 配置的点导航已弃用

为了减少复杂性、提高性能和增加可维护性，已弃用了通过点符号（config.a.b.c）访问配置的方法。这个功能将在将来的版本中被移除。

如果您通过点符号访问配置，还会看到警告消息。

推荐的访问配置的方式是：

[source,groovy]
----
grailsApplication.config.getProperty("hola", String.class)
----

### 弃用的类

* {apiDocs}org/grails/config/NavigableMap.html[org.grails.config.NavigableMap]
* {apiDocs}org/grails/config/NavigableMapConfig.html[org.grails.config.NavigableMapConfig]
* {apiDocs}org/grails/config/NavigableMapPropertySource.html[org.grails.config.NavigableMapPropertySource]

### Spring 5.3

Grails 5.0.0.RC1 是建立在 Spring 5.3.2 之上的。如果您正在使用 Spring 特定的功能，请查看 https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x# upgrading-to-version-53[升级至 Spring 5.3]。

### Spring Boot 2.4

Grails 5.1.1 更新到了 Spring Boot 2.6。请查看 https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes[Spring Boot 2.6 发布说明] 获取更多信息。

### Micronaut 3.2.0

Grails 5.1.1 附带了 Micronaut 3.2.0。如果您正在使用特定功能，请查看 https://docs.micronaut.io/3.2.0/guide/index.html#upgrading[升级至 Micronaut 3.x]。

### Micronaut for Spring 4.0.1

Grails 5.1.1 已更新为 Micronaut for Spring 4.0.1，请查看 https://github.com/micronaut-projects/micronaut-spring/releases/tag/v4.0.1[发布说明] 获取更多信息。

### Gradle 7.x

#### 在 Gradle 7.x 中已删除了编译依赖配置以及其他配置。在先前版本中，它们已被弃用。

替换配置：
[source, properties]
.build.gradle
----
...
 compile -> implementation
 testCompile -> testImplementation
 runtime -> runtimeOnly
...
----

注意：有关更多信息，请参阅 Gradle 升级文档 https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal[Gradle 升级文档]

#### 多项目设置中的插件

如果您在多项目构建的一部分中有 Grails 插件，则还应将 `compile` 替换为 `implementation` 配置。

此外，如果您的主应用程序依赖于插件声明的依赖项，则需要进行进一步的更改。

为了再次使依赖项可用，您必须使用 `api` 配置声明它们。您还必须在插件项目中应用 `java-library` gradle 插件。

注意：更多信息 https://docs.gradle.org/current/userguide/java_library_plugin.html[gradle java-library-plugin]