=== 步骤 1: 创建一个新项目

打开你的命令提示符或终端。

切换到你想要创建Grails项目的目录：

[source,shell]
----
$ cd your_project_directory
----

使用以下命令创建一个新的Grails项目：

[source,shell]
----
$ grails create-app myapp --servlet=tomcat
----

使用`--servlet`选项并设置值为"tomcat"指定了Grails应用程序应配置为使用嵌入式Tomcat Servlet容器作为其运行时环境，允许你在开发和测试过程中将应用程序作为独立可执行文件运行。

=== 步骤 2: 访问项目目录

进入你刚刚创建的"myapp"目录：

[source,shell]
----
$ cd myapp
----

=== 步骤 3: 启动Grails交互式控制台

通过运行"grails"命令启动Grails交互式控制台：

[source,shell]
----
$ grails
----

=== 步骤 4: 创建一个控制器

在Grails交互式控制台中，你可以使用自动完成功能来创建一个控制器。输入以下命令创建一个名为"greeting"的控制器：

[source,shell]
----
grails> create-controller greeting
----

此命令将在grails-app/controllers/myapp目录下生成一个名为"GreetingController.groovy"的新控制器。你可能会想知道为什么会有一个额外的"myapp"目录。这种结构符合Java开发中通常使用的约定，其中类被组织成包。Grails自动将应用程序名称包含在包结构中。如果你不指定包，Grails会默认使用应用程序名称。

有关创建控制器的更详细信息，你可以参考链接:../ref/Command%20Line/create-controller.html[create-controller]页面的文档。

=== 步骤 5: 编辑控制器

在文本编辑器中打开位于"grails-app/controllers/myapp"目录中的"GreetingController.groovy"文件。

向"GreetingController.groovy"文件中添加以下代码：

[source,groovy]
----
package myapp

class GreetingController {

    def index() {
        render "你好，恭喜你创建了你的第一个Grails应用程序！"
    }
}
----

该动作只是一个方法。在这种特定情况下，它调用了Grails提供的一个特殊方法来link:../ref/Controllers/render.html[渲染]页面。

=== 步骤 6: 运行应用程序

Grails框架现在依赖于Gradle任务来运行应用程序。要启动应用程序，请使用以下Gradle `bootRun`命令：

[source,shell]
----
$ ./gradlew bootRun
----

你的应用程序默认将托管在端口8080上。你可以在Web浏览器中通过以下地址访问它：

http://localhost:8080/

现在，重要的是要知道欢迎页面是由以下URL映射确定的：

[source,groovy]
----
class UrlMappings {
    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}
----

这个映射指定了根URL("/")应显示"index.gsp"视图，该视图位于"grails-app/views/index.gsp"。这个"index.gsp"文件充当你的欢迎页面或登陆页面。映射中的其他条目处理HTTP状态码500和404的错误页面。

**基于控制器和动作名称的Grails URL约定**

Grails遵循一种URL约定，该约定依赖于控制器和它们的动作的名称。这个约定简化了通过控制器和动作名称创建和访问各种页面或功能的过程。

在提供的代码示例中：

[source,groovy]
----
package myapp

class GreetingController {

    def index() {
        render "你好，恭喜你创建了你的第一个Grails应用程序！"
    }
}
----

- `GreetingController`类表示Grails中的一个控制器。

- 在控制器内部，有一个被定义为方法的`index`动作。在Grails中，动作本质上是控制器内处理特定任务或响应用户请求的方法。

现在，让我们了解根据这个控制器和动作如何工作的Grails URL约定：

1. *URL中的控制器名称：*
- 控制器名称，在这种情况下是"GreetingController"，被用于URL中。但是，约定将控制器名称的第一个字母大写，并删除"Controller"后缀。因此，在URL中"GreetingController"变成了"greeting"。

2. *URL中的动作名称：*
- 默认情况下，如果你在URL中不指定动作，Grails会假定"index"动作。因此，在这个示例中，访问URL`/greeting`

查看用户指南的链接结尾:theWebLayer.html#understandingControllersAndActions[控制器和动作]部分，了解更多关于默认动作的信息。

==== 可选: 设置上下文路径

如果你想为你的应用程序设置一个上下文路径，在"grails-app/conf/application.yml"文件中创建一个配置属性：

[source,yaml]
----
server:
    servlet:
        context-path: /myapp
----

通过这个配置，应用程序将在以下地址可用：

http://localhost:8080/myapp/

或者，当使用Gradle运行Grails应用程序时，你也可以从命令行设置上下文路径。下面是你可以这样做的方法：

[source,shell]
----
./gradlew bootRun -Dgrails.server.servlet.context-path=/your-context-path
----

将"/your-context-path"替换为你的Grails应用程序所需的上下文路径。这个命令通过`-Dgrails.server.servlet.context-path`系统属性直接设置上下文路径。

例如，如果你想让你的应用程序在"http://localhost:8080/myapp"上可用，你可以使用以下命令：

[source,shell]
----
./gradlew bootRun -Dgrails.server.servlet.context-path=/myapp
----

这样可以在不修改应用程序配置文件的情况下配置上下文路径，使其成为使用Gradle运行Grails应用程序时的一种灵活和方便的选择。

=== 可选: 更改服务器端口

如果端口8080已经被占用，你可以使用`grails.server.port`系统属性在不同的端口上启动服务器：

[source,shell]
----
$ ./gradlew bootRun --Dgrails.server.port=9090
----

将"9090"替换为你喜欢的端口。

=== Windows用户注意事项

如果你遇到与Java进程或文件名长度相关的错误，你可以使用`--stacktrace`标志或将`grails { pathingJar = true }`添加到你的"build.gradle"文件中。

=== 结论

当你在Web浏览器中访问时，你的Grails应用程序现在将显示一个"你好，恭喜你创建了你的第一个Grails应用程序！"的消息。

记住，你可以创建多个控制器和动作来构建更复杂的Grails Web应用程序。每个动作对应于根据控制器和动作名称访问的不同页面的不同页面。
