==== 可用范围

范围是类似哈希对象，您可以在其中存储变量。以下范围可供控制器使用：

* link:../ref/Controllers/servletContext.html[servletContext] - 也称为应用程序范围，该范围可以让您在整个Web应用程序中共享状态。servletContext是{javaee}javax/servlet/ServletContext.html[ServletContext]的一个实例
* link:../ref/Controllers/session.html[session] - 会话允许将状态与给定用户关联，并通常使用cookie将会话与客户端关联。会话对象是{javaee}javax/servlet/http/HttpSession.html[HttpSession]的一个实例
* link:../ref/Controllers/request.html[request] - 请求对象仅允许存储当前请求的对象。请求对象是{javaee}javax/servlet/http/HttpServletRequest.html[HttpServletRequest]的一个实例
* link:../ref/Controllers/params.html[params] - 可变映射，包含传入请求的查询字符串或POST参数
* link:../ref/Controllers/flash.html[flash] - 见下文

访问范围

可以使用上面的变量名与Groovy的数组索引运算符相结合来访问范围，甚至可以在Servlet API提供的类上使用，例如{javaee}javax/servlet/http/HttpServletRequest.html[HttpServletRequest]：

```groovy
类 BookController {
    def find() {
        def findBy = params["findBy"]
        def appContext = request["foo"]
        def loggedUser = session["logged_user"]
    }
}
```

您也可以使用反解引操作符访问范围内的值，这样语法变得更清晰：

```groovy
类 BookController {
    def find() {
        def findBy = params.findBy
        def appContext = request.foo
        def loggedUser = session.logged_user
    }
}
```

这是Grails统一访问不同范围的一种方式。

使用Flash范围

Grails支持将link:../ref/Controllers/flash.html[flash]范围作为临时存储，使属性仅在此请求和下一个请求中可用。然后清除属性。例如，在重定向之前直接设置消息很有用：

```groovy
def delete() {
    def b = Book.get(params.id)
    if (!b) {
        flash.message = "User not found for id ${params.id}"
        redirect(action:list)
    }
    // 剩余代码
}
```

请求 `delete` 时， `message` 值将在范围内，并可用于显示信息消息。在第二次请求后，它将从 `flash` 范围中删除。

请注意，属性名称可以是任意您想要的，并且通常是用于显示消息的字符串，但也可以是任何对象类型。

作用域控制器

新创建的应用程序在 `application.yml` 中将 `grails.controllers.defaultScope` 属性设置为“singleton”值。您可以将此值更改为下面列出的任何受支持的范围之一。如果未分配任何值属性，默认控制器将默认为“prototype”范围。

支持的控制器范围包括：

* `prototype` （默认）- 为每个请求创建一个新的控制器（建议用于作为Closure属性的操作）
* `session` - 为用户会话范围创建一个控制器
* `singleton` - 仅存在一个控制器实例（建议用作方法的操作）

要激活其中一个范围，请向您的类添加一个静态 `scope` 属性，其值为前面列出的任何有效范围之一，例如：

```groovy
静态范围 = “singleton”
```

您可以在 `application.yml` 中使用 `grails.controllers.defaultScope` 键来定义默认的策略，例如：

```groovy
grails:
    controllers:
        defaultScope: singleton
```

注意：明智地使用作用域控制器。例如，我们不建议在具有单例作用域的控制器中拥有任何属性，因为它们将用于所有请求。"