==== 程序化文件上传

Grails支持使用Spring的 {springapi}org/springframework/web/multipart/MultipartHttpServletRequest.html[MultipartHttpServletRequest]接口进行文件上传。文件上传的第一步是创建一个类似于以下的多部分表单：

[source,xml]
----
上传表单：<br />
    <g:uploadForm action=\"upload\">
        <input type=\"file\" name=\"myFile\" />
        <input type=\"submit\" />
    </g:uploadForm>
----

`uploadForm` 标签方便地将 `enctype=\"multipart/form-data\"` 属性添加到标准的 `<g:form>` 标签中。

然后有许多处理文件上传的方法。一种方法是直接使用Spring {springapi}org/springframework/web/multipart/MultipartFile.html[MultipartFile]实例进行操作：

[source,groovy]
----
def upload() {
    def f = request.getFile('myFile')
    if (f.empty) {
        flash.message = 'file cannot be empty'
        render(view: 'uploadForm')
        return
    }

    f.transferTo(new File('/some/local/dir/myfile.txt'))
    response.sendError(200, 'Done')
}
----

这对于将文件传输到其他目的地并直接操作文件非常方便，因为您可以使用 {springapi}org/springframework/web/multipart/MultipartFile.html[MultipartFile]接口获取 `InputStream` 等内容。

==== 数据绑定进行文件上传

也可以使用数据绑定来执行文件上传。考虑这个 `Image` 领域类：

[source,groovy]
----
class Image {
    byte[] myFile

    static constraints = {
        // 将上传文件大小限制为2MB
        myFile maxSize: 1024 * 1024 * 2
    }
}
----

如果您在构造函数中使用 `params` 对象创建图像，如下面的示例，Grails将自动将文件内容绑定为 ` byte[]` 到 `myFile` 属性：

[source,groovy]
----
def img = new Image(params)
----

您应该设置 link:../ref/Constraints/size.html[size]或 link:../ref/Constraints/maxSize.html[maxSize]约束，否则您的数据库可能会创建带有无法容纳合理大小文件的小列大小。例如，H2和MySQL默认将 ` byte[]` 属性的blob大小设置为255字节。

还可以通过将图像上的 `myFile` 属性的类型更改为String类型，将文件的内容设置为字符串：

[source,groovy]
----
class Image {
   String myFile
}
----

==== 增加上传的最大文件大小

Grails的文件上传默认大小为128000（约128KB）。当超过此限制时，您将看到以下异常：

[source,java]
----
org.springframework.web.multipart.MultipartException: Could not parse multipart servlet request; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.FileUploadBase$SizeLimitExceededException
----

您可以在您的 `application.yml` 中配置限制如下：

[source,yml]
.grails-app/conf/application.yml
----
grails:
    controllers:
        upload:
            maxFileSize: 2000000
            maxRequestSize: 2000000
----

`maxFileSize` = 允许上传文件的最大大小。

`maxRequestSize` = 允许multipart/form-data请求的最大大小。

请谨记 https://www.owasp.org/index.php/Unrestricted_File_Upload[OWASP建议-无限制文件上传]

注意：限制文件大小到最大值以防止拒绝服务攻击。

这些限制存在是为了防止DoS攻击并强制执行整体应用程序性能。